# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [2]:
import numpy as np

a = np.arange(100)

print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

%timeit a.sum()
%timeit np.sum(a)
%timeit sum(a)

4950
4950
4950
1.88 µs ± 31.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2.53 µs ± 15.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
9.53 µs ± 93.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


三者得到的結果相同，但計算的速度不同：a.sum > np.sum(a) > sum(a)

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [5]:
# 記得先 Import 正確的套件
import numpy as np

A = np.random.random((5, 5))
normalA = (A-A.min())/(A.max()-A.min())
print(A,normalA,sep='\n') # sep='\n'為元素之間分隔(seperate)的方法，意即換行

[[0.41410494 0.54263535 0.83175762 0.72931193 0.8828148 ]
 [0.51820006 0.31217833 0.49674835 0.46100478 0.65026448]
 [0.74801666 0.75469957 0.54581096 0.71660841 0.91960615]
 [0.53780745 0.64394612 0.11129027 0.3924574  0.13576376]
 [0.89883599 0.45994535 0.2013675  0.37583324 0.17450426]]
[[0.37462417 0.53363429 0.89131906 0.76457938 0.95448394]
 [0.50340441 0.24852667 0.47686565 0.43264584 0.66678661]
 [0.78771976 0.79598744 0.53756297 0.74886335 1.        ]
 [0.52766151 0.65896992 0.         0.34784313 0.03027713]
 [0.9743044  0.43133518 0.11143815 0.32727671 0.07820455]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [7]:
A = np.random.randint(1,50,10)
print(A)
A[A==np.max(A)]=-1
print(A)

[29 28  5 39 36  5 17 27 36 24]
[29 28  5 -1 36  5 17 27 36 24]


### 4. 將下列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")

In [11]:
array1 = np.array(range(30))
print (array1)
print('按列填充:',array1.reshape(5,6,order='F'),sep='\n')
print('按列填充:',array1.reshape(5,6,order='C'),sep='\n')
array2 = array1.reshape(5,6,order='F')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
按列填充:
[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]
按列填充:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


### 5.呈上題的 array，找出被 6 除餘 1 的數的索引

In [12]:
np.where(array2%6==1)

(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))

In [27]:
print(array2[0,5]) 
print(array2[1,0])
print(array2[2,1])
print(array2[3,2]) 
print(array2[4,3])
#根據索引位置找出該元素

25
1
7
13
19


In [28]:
array2[np.where(array2%6==1)] 
#找出被 6 除餘 1 的數

array([25,  1,  7, 13, 19])